# Caffeine Configuration
spring:
  cache:
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=600s
    cache-names:
      - buckets

# Redis Configuration
#spring:
#  cache:
#    cache-names:
#      - buckets
#  redis:
#    host: localhost
#    port: 6379

# Hazelcast Configuration
#spring:
#  cache:
#    jcache:
#      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
#      config: classpath:hazelcast.xml
#    cache-names:
#      - buckets

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /first(/|\?)?.*
      rate-limits:
        - expression: "@securityService.getClientIP(#this)"
          bandwidths:
            - capacity: 1
              time: 5
              unit: seconds
    - cache-name: buckets
      url: /second(/|\?)?.*
      rate-limits:
        - expression: "@securityService.getClientIP(#this)"
          bandwidths:
            - capacity: 2
              time: 5
              unit: seconds