spring:
  cache:
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s
    cache-names:
      - buckets

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /first(/|\?)?.*
      rate-limits:
        - expression: "@securityService.getClientIP(#this)"
          bandwidths:
            - capacity: 1
              time: 5
              unit: seconds
    - cache-name: buckets
      url: /second(/|\?)?.*
      rate-limits:
        - expression: "@securityService.getClientIP(#this)"
          bandwidths:
            - capacity: 2
              time: 5
              unit: seconds